import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import { config } from './config.js';
import { authRouter } from './routes/auth.js';
import { guardsRouter } from './routes/guards.js';
import { managersRouter } from './routes/managers.js';
import { attendanceRouter } from './routes/attendance.js';
import { salaryRouter } from './routes/salary.js';
import { reportsRouter } from './routes/reports.js';
import { locationsRouter } from './routes/locations.js';
import { dashboardRouter } from './routes/dashboard.js';
import { errorHandler, notFound } from './lib/http.js';

export const app = express();
app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: config.WEB_ORIGIN.split(',').map((origin) => origin.trim()), credentials: false }));
app.use(express.json({ limit: '1mb' }));
app.use(morgan(config.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.get('/api/health', (_req, res) => res.json({ status: 'ok', service: 'secattend-api', timestamp: new Date().toISOString() }));
app.use('/api/auth/login', rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: 'draft-7', legacyHeaders: false }));
app.use('/api/auth', authRouter);
app.use('/api/dashboard', dashboardRouter);
app.use('/api/locations', locationsRouter);
app.use('/api/guards', guardsRouter);
app.use('/api/managers', managersRouter);
app.use('/api/attendance', attendanceRouter);
app.use('/api/salary', salaryRouter);
app.use('/api/reports', reportsRouter);
app.use(notFound);
app.use(errorHandler);
