import { useCallback, useEffect, useMemo, useState } from 'react';
import { addMonths, eachDayOfInterval, endOfMonth, format, getDay, isAfter, isSameDay, startOfMonth, subMonths } from 'date-fns';
import { CalendarCheck, Check, ChevronLeft, ChevronRight, Clock3, Palmtree, Save } from 'lucide-react';
import { api } from '../lib/api';
import type { AttendanceStatus, Guard } from '../types';
import { Avatar, LoadingState, PageHeader, Toast } from '../components/ui';

type DaySummary = { date: string; marked: number; present: number; leave: number; total: number; state: string };
export function AttendancePage() {
  const [month, setMonth] = useState(startOfMonth(new Date())); const [selected, setSelected] = useState(new Date()); const [summary, setSummary] = useState<DaySummary[]>([]); const [guards, setGuards] = useState<Guard[]>([]); const [records, setRecords] = useState<Record<string, AttendanceStatus>>({});
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [editable, setEditable] = useState(true); const [toast, setToast] = useState('');
  const monthKey = format(month, 'yyyy-MM'); const dateKey = format(selected, 'yyyy-MM-dd');
  const loadSummary = useCallback(() => api<{ data: DaySummary[] }>(`/attendance/calendar/summary?month=${monthKey}`).then((result) => setSummary(result.data)), [monthKey]);
  const loadDay = useCallback(async () => { setLoading(true); try { const result = await api<{ data: Guard[]; editable: boolean }>(`/attendance/${dateKey}`); setGuards(result.data); setRecords(Object.fromEntries(result.data.filter((g) => g.attendance).map((g) => [g.id, g.attendance!.status]))); setEditable(result.editable && !isAfter(selected, new Date())); } finally { setLoading(false); } }, [dateKey, selected]);
  useEffect(() => { loadSummary(); }, [loadSummary]); useEffect(() => { loadDay(); }, [loadDay]);
  const summaryMap = useMemo(() => new Map(summary.map((item) => [item.date, item])), [summary]);
  const days = eachDayOfInterval({ start: startOfMonth(month), end: endOfMonth(month) }); const blanks = Array.from({ length: getDay(startOfMonth(month)) });
  function statusFor(day: Date) { if (isAfter(day, new Date())) return 'future'; const item = summaryMap.get(format(day, 'yyyy-MM-dd')); return item?.state ?? 'none'; }
  function markAll() { setRecords(Object.fromEntries(guards.map((guard) => [guard.id, 'PRESENT']))); }
  async function save() { const values = Object.entries(records).map(([guardId, status]) => ({ guardId, status })); if (!values.length) return; setSaving(true); try { await api(`/attendance/${dateKey}`, { method: 'POST', body: JSON.stringify({ records: values }) }); setToast(`${values.length} attendance records saved`); await Promise.all([loadDay(), loadSummary()]); } catch (err) { setToast(err instanceof Error ? err.message : 'Unable to save attendance'); } finally { setSaving(false); } }
  return <div className="page"><PageHeader eyebrow="Daily field operations" title="Attendance" description="Review calendar completion and mark every guard’s shift status." actions={<button className="button button--primary" onClick={save} disabled={!editable || saving || !Object.keys(records).length}><Save size={17} />{saving ? 'Saving…' : 'Save attendance'}</button>} />
    <section className="attendance-layout"><article className="panel calendar-card"><header><button className="icon-button" onClick={() => setMonth(subMonths(month, 1))} aria-label="Previous month"><ChevronLeft /></button><h2>{format(month, 'MMMM yyyy')}</h2><button className="icon-button" onClick={() => setMonth(addMonths(month, 1))} aria-label="Next month"><ChevronRight /></button></header><div className="calendar-weekdays">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{blanks.map((_, index) => <span key={`blank-${index}`} />)}{days.map((day) => { const state = statusFor(day); return <button key={day.toISOString()} className={`${state} ${isSameDay(day, selected) ? 'selected' : ''} ${isSameDay(day, new Date()) ? 'today' : ''}`} disabled={state === 'future'} onClick={() => setSelected(day)}><span>{format(day, 'd')}</span><i />{summaryMap.get(format(day, 'yyyy-MM-dd')) && <small>{summaryMap.get(format(day, 'yyyy-MM-dd'))!.marked}/{summaryMap.get(format(day, 'yyyy-MM-dd'))!.total}</small>}</button>; })}</div><footer className="calendar-legend"><span><i className="complete" />Complete</span><span><i className="partial" />Partial</span><span><i className="none" />Unmarked</span></footer></article>
      <article className="panel attendance-sheet"><header className="attendance-sheet__header"><div><p className="eyebrow">Attendance sheet</p><h2>{format(selected, 'EEEE, d MMMM')}</h2><p>{guards.length} assigned guards · {Object.keys(records).length} marked</p></div><div>{editable ? <span className="editable-chip"><Clock3 size={14} />Editing open</span> : <span className="locked-chip">Attendance locked</span>}<button className="button button--secondary button--small" onClick={markAll} disabled={!editable}><Check size={16} />Mark all present</button></div></header>{loading ? <LoadingState /> : <div className="attendance-list">{guards.map((guard) => <div className="attendance-row" key={guard.id}><div className="person-cell"><Avatar name={guard.name} /><div><strong>{guard.name}</strong><span>{guard.employeeId} · {guard.location.name}</span></div></div><div className="attendance-toggle"><button disabled={!editable} className={records[guard.id] === 'PRESENT' ? 'active present' : ''} onClick={() => setRecords({ ...records, [guard.id]: 'PRESENT' })}><CalendarCheck size={17} />Present</button><button disabled={!editable} className={records[guard.id] === 'ON_LEAVE' ? 'active leave' : ''} onClick={() => setRecords({ ...records, [guard.id]: 'ON_LEAVE' })}><Palmtree size={17} />On leave</button></div></div>)}</div>}<footer className="attendance-sheet__footer"><span>{Object.keys(records).length === guards.length ? <><Check size={15} /> All guards marked</> : `${guards.length - Object.keys(records).length} guards still unmarked`}</span><button className="button button--primary" onClick={save} disabled={!editable || saving}>{saving ? 'Saving…' : `Save ${Object.keys(records).length} records`}</button></footer></article></section>{toast && <Toast message={toast} onClose={() => setToast('')} />}</div>;
}
