import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { Download, FileSpreadsheet, MapPin, MoreHorizontal, Plus, Search, ShieldCheck, Upload, UserRound } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { api, currency } from '../lib/api';
import type { Guard, Location } from '../types';
import { Avatar, EmptyState, LoadingState, Modal, PageHeader, Toast } from '../components/ui';

type GuardForm = { name: string; employeeId: string; phone: string; email: string; address: string; locationId: string; guardMonthlySalary: string; companyMonthlySalary: string };
const emptyForm: GuardForm = { name: '', employeeId: '', phone: '', email: '', address: '', locationId: '', guardMonthlySalary: '', companyMonthlySalary: '' };

export function GuardsPage() {
  const { user } = useAuth(); const [guards, setGuards] = useState<Guard[]>([]); const [locations, setLocations] = useState<Location[]>([]);
  const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [locationId, setLocationId] = useState(''); const [status, setStatus] = useState('ACTIVE');
  const [modal, setModal] = useState<'form' | 'import' | null>(null); const [editing, setEditing] = useState<Guard | null>(null); const [form, setForm] = useState<GuardForm>(emptyForm); const [toast, setToast] = useState(''); const [busy, setBusy] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null); const [importResult, setImportResult] = useState<{ imported: number; rejected: number; errors: { row: number; message: string }[] } | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const query = new URLSearchParams({ search, status, ...(locationId && { locationId }), pageSize: '100' }); const result = await api<{ data: Guard[] }>(`/guards?${query}`); setGuards(result.data); } finally { setLoading(false); } }, [search, status, locationId]);
  useEffect(() => { api<{ data: Location[] }>('/locations').then((r) => setLocations(r.data)); }, []);
  useEffect(() => { const id = setTimeout(load, 250); return () => clearTimeout(id); }, [load]);
  function openForm(guard?: Guard) { setEditing(guard ?? null); setForm(guard ? { name: guard.name, employeeId: guard.employeeId, phone: guard.phone, email: guard.email ?? '', address: guard.address, locationId: guard.locationId, guardMonthlySalary: String(guard.guardMonthlySalary), companyMonthlySalary: String(guard.companyMonthlySalary) } : { ...emptyForm, locationId: locations[0]?.id ?? '' }); setModal('form'); }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); try { await api(editing ? `/guards/${editing.id}` : '/guards', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(form) }); setModal(null); setToast(editing ? 'Guard details updated' : 'Guard added to the roster'); await load(); } catch (err) { setToast(err instanceof Error ? err.message : 'Could not save guard'); } finally { setBusy(false); } }
  async function importFile() { const file = fileRef.current?.files?.[0]; if (!file) return; setBusy(true); const body = new FormData(); body.append('file', file); try { const result = await api<typeof importResult>('/guards/import/excel', { method: 'POST', body }); setImportResult(result); setToast(`Imported ${result?.imported ?? 0} guards`); await load(); } catch (err) { setToast(err instanceof Error ? err.message : 'Import failed'); } finally { setBusy(false); } }
  return <div className="page">
    <PageHeader eyebrow="People & deployment" title="Guard roster" description="Manage personnel records, assignments, and salary details." actions={user!.role === 'ADMIN' && <><button className="button button--secondary" onClick={() => { setImportResult(null); setModal('import'); }}><Upload size={17} />Import Excel</button><button className="button button--primary" onClick={() => openForm()}><Plus size={18} />Add guard</button></>} />
    <section className="toolbar"><div className="search-box"><Search size={18} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name, ID or phone…" aria-label="Search guards" /></div><select value={locationId} onChange={(e) => setLocationId(e.target.value)} aria-label="Filter by location"><option value="">All locations</option>{locations.map((location) => <option value={location.id} key={location.id}>{location.name}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Filter by status"><option value="ACTIVE">Active guards</option><option value="INACTIVE">Inactive guards</option></select><span className="toolbar__count">{guards.length} records</span></section>
    <section className="table-card">{loading ? <LoadingState /> : guards.length === 0 ? <EmptyState icon={<ShieldCheck />} title="No guards found" description="Try adjusting your filters or add the first guard." /> : <div className="data-table-wrap"><table className="data-table roster-table"><thead><tr><th>Guard</th><th>Employee ID</th><th>Assignment</th><th>Contact</th>{user!.role === 'ADMIN' && <><th>Guard pay</th><th>Company billing</th></>}<th>Status</th>{user!.role === 'ADMIN' && <th><span className="sr-only">Actions</span></th>}</tr></thead><tbody>{guards.map((guard) => <tr key={guard.id}><td data-label="Guard"><div className="person-cell"><Avatar name={guard.name} /><div><strong>{guard.name}</strong><span>{guard.email || 'No email provided'}</span></div></div></td><td data-label="Employee ID"><span className="mono-id">{guard.employeeId}</span></td><td data-label="Assignment"><span className="location-tag"><MapPin size={14} />{guard.location.name}</span></td><td data-label="Contact"><strong className="cell-main">{guard.phone}</strong><span className="cell-sub">{guard.address}</span></td>{user!.role === 'ADMIN' && <><td data-label="Guard pay"><strong className="salary-cell">{currency(guard.guardMonthlySalary)}</strong><span className="cell-sub">In-hand base</span></td><td data-label="Company billing"><strong className="salary-cell">{currency(guard.companyMonthlySalary)}</strong><span className="cell-sub">Agency invoice</span></td></>}<td data-label="Status"><span className={`status-badge status-badge--${guard.status.toLowerCase()}`}><i />{guard.status.toLowerCase()}</span></td>{user!.role === 'ADMIN' && <td className="row-action"><button className="icon-button" onClick={() => openForm(guard)} aria-label={`Edit ${guard.name}`}><MoreHorizontal /></button></td>}</tr>)}</tbody></table></div>}</section>
    <Modal open={modal === 'form'} title={editing ? 'Edit guard record' : 'Add a new guard'} description="Keep personnel, deployment, and both salary figures accurate." onClose={() => setModal(null)} size="lg"><form className="form-grid" onSubmit={save}><label>Full name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Employee ID<input value={form.employeeId} onChange={(e) => setForm({ ...form, employeeId: e.target.value })} required /></label><label>Phone number<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} required /></label><label>Email address<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label className="form-grid__wide">Address<textarea value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} required /></label><label>Assigned location<select value={form.locationId} onChange={(e) => setForm({ ...form, locationId: e.target.value })} required><option value="">Select location</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><label>Guard in-hand salary (₹)<input type="number" min="1" value={form.guardMonthlySalary} onChange={(e) => setForm({ ...form, guardMonthlySalary: e.target.value })} required /></label><label>Company billing salary (₹)<input type="number" min="1" value={form.companyMonthlySalary} onChange={(e) => setForm({ ...form, companyMonthlySalary: e.target.value })} required /></label><footer className="modal__actions"><button type="button" className="button button--ghost" onClick={() => setModal(null)}>Cancel</button><button className="button button--primary" disabled={busy}>{busy ? 'Saving…' : editing ? 'Save changes' : 'Add guard'}</button></footer></form></Modal>
    <Modal open={modal === 'import'} title="Import guard roster" description="Upload an .xlsx file and we’ll validate every row before import." onClose={() => setModal(null)}><div className="import-zone"><FileSpreadsheet size={34} /><strong>Choose an Excel workbook</strong><p>Columns: Name, EmployeeID, Phone, Email, Address, Location, GuardMonthlySalary, CompanyMonthlySalary</p><input ref={fileRef} type="file" accept=".xlsx,.xls" /><button className="button button--primary" onClick={importFile} disabled={busy}><Download size={17} />{busy ? 'Validating…' : 'Validate & import'}</button></div>{importResult && <div className="import-result"><strong>{importResult.imported} imported · {importResult.rejected} rejected</strong>{importResult.errors.slice(0, 5).map((error) => <p key={error.row}>Row {error.row}: {error.message}</p>)}</div>}</Modal>
    {toast && <Toast message={toast} onClose={() => setToast('')} />}
  </div>;
}
