import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { MapPin, MoreHorizontal, Plus, Search, Users } from 'lucide-react';
import { api } from '../lib/api';
import type { Location, Manager } from '../types';
import { Avatar, EmptyState, LoadingState, Modal, PageHeader, Toast } from '../components/ui';

type ManagerForm = { name: string; email: string; phone: string; password: string; locationIds: string[] };
const emptyForm: ManagerForm = { name: '', email: '', phone: '', password: '', locationIds: [] };

export function ManagersPage() {
  const [managers, setManagers] = useState<Manager[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Manager | null>(null); const [form, setForm] = useState<ManagerForm>(emptyForm); const [busy, setBusy] = useState(false); const [toast, setToast] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const result = await api<{ data: Manager[] }>(`/managers?search=${encodeURIComponent(search)}&pageSize=100`); setManagers(result.data); } finally { setLoading(false); } }, [search]);
  useEffect(() => { const id = setTimeout(load, 250); return () => clearTimeout(id); }, [load]);
  useEffect(() => { api<{ data: Location[] }>('/locations').then((result) => setLocations(result.data)); }, []);
  function edit(manager?: Manager) { setEditing(manager ?? null); setForm(manager ? { name: manager.name, email: manager.email, phone: manager.phone, password: '', locationIds: manager.locations.map((l) => l.id) } : emptyForm); setOpen(true); }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); try { const payload = { ...form, ...(!form.password && { password: undefined }) }; await api(editing ? `/managers/${editing.id}` : '/managers', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); setOpen(false); setToast(editing ? 'Manager profile updated' : 'Manager account created'); await load(); } catch (err) { setToast(err instanceof Error ? err.message : 'Unable to save manager'); } finally { setBusy(false); } }
  function toggleLocation(id: string) { setForm((current) => ({ ...current, locationIds: current.locationIds.includes(id) ? current.locationIds.filter((item) => item !== id) : [...current.locationIds, id] })); }
  return <div className="page"><PageHeader eyebrow="Access & accountability" title="Managers" description="Assign site leadership and control operational access." actions={<button className="button button--primary" onClick={() => edit()}><Plus size={18} />Add manager</button>} />
    <section className="toolbar"><div className="search-box"><Search size={18} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search manager name or email…" /></div><span className="toolbar__count">{managers.length} managers</span></section>
    <section className="manager-grid">{loading ? <LoadingState /> : managers.length === 0 ? <EmptyState icon={<Users />} title="No managers found" description="Add a manager and assign their operational locations." /> : managers.map((manager) => <article className="manager-card" key={manager.id}><header><Avatar name={manager.name} size="lg" /><span className={`status-badge status-badge--${manager.status.toLowerCase()}`}><i />{manager.status.toLowerCase()}</span><button className="icon-button" onClick={() => edit(manager)} aria-label={`Edit ${manager.name}`}><MoreHorizontal /></button></header><h3>{manager.name}</h3><p>{manager.email}</p><p>{manager.phone}</p><div className="manager-card__locations"><span>Assigned locations</span>{manager.locations.map((location) => <strong key={location.id}><MapPin size={14} />{location.name}</strong>)}</div><footer><span>Added {new Intl.DateTimeFormat('en-IN', { month: 'short', year: 'numeric' }).format(new Date(manager.createdAt))}</span><button onClick={() => edit(manager)}>View profile</button></footer></article>)}</section>
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Edit manager' : 'Add manager'} description="Managers can mark attendance for guards at assigned locations." size="lg"><form className="form-grid" onSubmit={save}><label>Full name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Phone number<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} required /></label><label>Email address<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></label><label>{editing ? 'New password (optional)' : 'Temporary password'}<input type="password" minLength={8} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required={!editing} /></label><fieldset className="form-grid__wide location-picker"><legend>Assigned locations</legend>{locations.map((location) => <label key={location.id} className={form.locationIds.includes(location.id) ? 'selected' : ''}><input type="checkbox" checked={form.locationIds.includes(location.id)} onChange={() => toggleLocation(location.id)} /><MapPin size={18} /><span><strong>{location.name}</strong><small>{location.address}</small></span></label>)}</fieldset><footer className="modal__actions"><button type="button" className="button button--ghost" onClick={() => setOpen(false)}>Cancel</button><button className="button button--primary" disabled={busy || form.locationIds.length === 0}>{busy ? 'Saving…' : editing ? 'Save changes' : 'Create manager'}</button></footer></form></Modal>{toast && <Toast message={toast} onClose={() => setToast('')} />}</div>;
}
