import { useCallback, useEffect, useState } from 'react';
import { Calculator, Download, RefreshCw, Search, WalletCards } from 'lucide-react';
import { format, subMonths } from 'date-fns';
import { api, currency } from '../lib/api';
import { Avatar, EmptyState, LoadingState, PageHeader, Toast } from '../components/ui';

type SalaryRow = { id: string; totalDays: number; leaveDays: number; dailyRate: string; grossSalary: string; deductions: string; netSalary: string; generatedAt: string; guard: { id: string; name: string; employeeId: string; location: { name: string } } };
export function PayrollPage() {
  const [month, setMonth] = useState(format(subMonths(new Date(), 1), 'yyyy-MM')); const [rows, setRows] = useState<SalaryRow[]>([]); const [totals, setTotals] = useState({ gross: 0, deductions: 0, net: 0 }); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [search, setSearch] = useState(''); const [toast, setToast] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const result = await api<{ data: SalaryRow[]; totals: typeof totals }>(`/salary/${month}`); setRows(result.data); setTotals(result.totals); } finally { setLoading(false); } }, [month]);
  useEffect(() => { load(); }, [load]);
  async function calculate() { setBusy(true); try { const result = await api<{ generated: number }>(`/salary/calculate/${month}`, { method: 'POST' }); setToast(`Payroll calculated for ${result.generated} guards`); await load(); } catch (err) { setToast(err instanceof Error ? err.message : 'Calculation failed'); } finally { setBusy(false); } }
  const filtered = rows.filter((row) => `${row.guard.name} ${row.guard.employeeId}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="page"><PageHeader eyebrow="Compensation operations" title="Payroll" description="Calculate leave deductions and review monthly salary summaries." actions={<><button className="button button--secondary" disabled={!rows.length}><Download size={17} />Export summary</button><button className="button button--primary" onClick={calculate} disabled={busy}><Calculator size={17} />{busy ? 'Calculating…' : 'Calculate payroll'}</button></>} />
    <section className="payroll-controls"><label>Payroll month<input type="month" value={month} onChange={(e) => setMonth(e.target.value)} /></label><div className="search-box"><Search size={17} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Find a guard…" /></div><button className="icon-button" onClick={load} aria-label="Refresh payroll"><RefreshCw size={18} /></button></section>
    <section className="payroll-summary"><article><span>Gross payroll</span><strong>{currency(totals.gross)}</strong><p>Before deductions</p></article><article><span>Leave deductions</span><strong>{currency(totals.deductions)}</strong><p>Based on daily rates</p></article><article className="payroll-summary__net"><span>Net payable</span><strong>{currency(totals.net)}</strong><p>Across {rows.length} guards</p></article></section>
    <section className="table-card">{loading ? <LoadingState /> : !filtered.length ? <EmptyState icon={<WalletCards />} title="Payroll not calculated" description="Choose a month and calculate payroll to generate salary records." /> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Guard</th><th>Location</th><th>Daily rate</th><th>Leave days</th><th>Gross salary</th><th>Deductions</th><th>Net salary</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td><div className="person-cell"><Avatar name={row.guard.name} /><div><strong>{row.guard.name}</strong><span>{row.guard.employeeId}</span></div></div></td><td>{row.guard.location.name}</td><td>{currency(row.dailyRate)}</td><td><span className={row.leaveDays ? 'leave-count' : ''}>{row.leaveDays}</span></td><td>{currency(row.grossSalary)}</td><td className="deduction">− {currency(row.deductions)}</td><td><strong className="salary-cell">{currency(row.netSalary)}</strong></td></tr>)}</tbody></table></div>}</section>{toast && <Toast message={toast} onClose={() => setToast('')} />}</div>;
}
